services:
    db:
        image: neo4j:community
        ports:
            - "7687:7687"
            - "7474:7474"
        volumes:
            - neo4j_data:/data
        environment:
            NEO4J_AUTH: neo4j/neo4jpw4neo4j

    backend:
        build: ./backend/
        container_name: backend
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
    
    frontend:
        build: ./frontend/
        container_name: frontend
        ports:
            - "5173:5173"
        depends_on:
            - backend
volumes:
    neo4j_data:
