"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from neomodel import config
from dotenv import load_dotenv
import os
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO : Mettre générer une nouvelle clé secrète dans un fichier de configuration séparé pour éviter de la hardcoder dans le code
SECRET_KEY = "django-insecure-l4u@!%q!92pin=b=4u)lr2@u+bt*rqhz43s4nz1%%#+dc@2!ln"

# SECURITY WARNING: don't run with debug turned on in production!
# TODO : à changer en False pour la production (True en développement)
DEBUG = True

# TODO : à adapter pour la production, doit accepter le frontend (ex: ['mon-domaine.com'])
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # "rest_framework_simplejwt.token_blacklist", (incompatible avec neo4j)
    "django_extensions",
    "corsheaders",
    "API",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "API.auth.Neo4jJWTAuthentication",
    ],
    # Permission par défaut d'accès à toutes les vues
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.IsAuthenticatedOrReadOnly",  # Visiteur autorisé pour 'GET', 'HEAD', 'OPTIONS' sinon connexion
        "API.permissions.IsAdminOrReadOnly",  # Nécessite l'auth pour toute action (mesure de sécurité) sinon admin
    ],
}

# TODO exporter la configuration de JWT dans un fichier de configuration séparé pour l'importer correctement et éviter les impmorts circulaires
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=30
    ),  # Temps de vie d'un token d'accès (à redéfinir)
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7
    ),  # Temps de vie d'un token refresh (à redéfinir)
    # "BLACKLIST_AFTER_ROTATION": True,  # Quand claim d'un nouveau token refresh, supprime l'ancien (incompatible avec neo4j)
    "ALGORITHM": "HS256",  # Algorithme de chiffrement
    "SIGNING_KEY": SECRET_KEY,  # Clé de chiffrement
    "AUDIENCE": "API",  # Actif sur l'application API
    "AUTH_HEADER_TYPES": ("Bearer",),  # Prefix du token du header Autorization
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",  # Nom du champ du header du token access
    "USER_ID_FIELD": "uuid",  # Champ d'utilisateur pour la génération des tokens
    "USER_ID_CLAIM": "user_uuid",  # Nom du champ dans le token
    "CHECK_REVOKE_TOKEN": True,  # Révoque les tokens en cas de changement de mdp
    "REVOKE_TOKEN_CLAIM": "password",  # Fonction de changement de mot de passe
    "TOKEN_OBTAIN_SERIALIZER": "API.serializers.TokenObtain",  # Serializer d'obtention des tokens (access et refresh)
    "TOKEN_REFRESH_SERIALIZER": "API.serializers.TokenRefresh",  # Serializer d'obtention du token access à partir de refresh
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Par défaut en anglais
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# En français
# LANGUAGE_CODE = 'fr'

# USE_I18N = True
# USE_L10N = True

# LANGUAGES = [
#     ('fr', 'Français'),
# ]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

load_dotenv()  # charge le .env

NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
NEO4J_HOST = os.getenv("NEO4J_HOST")
NEO4J_PORT = os.getenv("NEO4J_PORT")

config.DATABASE_URL = f"bolt://{NEO4J_USER}:{NEO4J_PASSWORD}@{NEO4J_HOST}:{NEO4J_PORT}"
TEST_RUNNER = "backend.runner.CustomTestRunner"

# TODO : à adapter pour la production, doit accepter le frontend (ex: ['http://localhost:5173'] en développement, avec 5173 le port du frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
